### ISSUE TITLE
Add Istio Gateway Support

### ISSUE THREAD

**Issue by danehans** [solo-io/service-mesh-hub#161]
I use Istio `VirtualService` and `Gateway` resources to expose services outside a mesh. Currently, SuperGloo does not support the `Gateway` resource. I am interested in submitting a PR to add this support with some guidance.

**Comment by ilackarms** [comment]
Ingress/Gateway support is on our roadmap. We'd be happy to accept contributions to this effect. What do you imagine the SuperGloo API looking like for this feature?

**Comment by GrahamGoudeau** [comment]
Outdated- closing
