### ISSUE TITLE
Consul Connect

### ISSUE THREAD

**Issue by fagurto** [solo-io/service-mesh-hub#463]
looking at the docs , it seems there is no examples of configure supoergloo with consul connect , is there any example ? or future plans to include this in the documentation ?

**Comment by ilackarms** [comment]
@fagurto consul connect was supported in an older version of supergloo, but we lost support when we did a large-scale rewrite of supergloo. we haven't gotten around to reimplementing support. i can't say where it is on our current priority list, but it is a feature request we've had from a number of users.

**Comment by GrahamGoudeau** [comment]
Outdated issue; consul connect support is coming up soon in our list of priorities, but closing out this issue to clean things up
