### ISSUE TITLE
Consider using default AWS credential provider

### ISSUE THREAD

**Issue by sbuzonas** [solo-io/service-mesh-hub#493]
The AWS SDK provides a default credential provider. Consider refactoring the current secrets based implementation to a credential provider and add it to the chain provider. This will open up a number of different ways the user can configure authenticating with AWS.  InstanceProfile credentials in particular.

I have a use case where we have a policy that we do not issue API keys for services. Everything is done via InstanceProfile assume role or sts temporary credentials in the env provided by vault.

**Comment by GrahamGoudeau** [comment]
Closing this out as it's a pretty old issue- @sbuzonas if you're still interested in AWS use cases here, we have some updated AWS docs coming soon. Feel free to open another issue with any questions or reach out to us on Slack!

**Comment by sbuzonas** [comment]
It still doesn't seem to work with an instance profile.
