### ISSUE TITLE
Decouple meshctl install from cluster register implementation

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#547]
meshctl install should not call directly into the cluster register implementation. The registration function should be pulled, together with the deregister method, into a single RegistrationClient component that can do both registration and de-registration

**Comment by harveyxia** [comment]
This has been completed in https://github.com/solo-io/service-mesh-hub/pull/673, with the qualification that we separate clients for Registration and Deregistration (they take different dependencies so we decided to split them into distinct interfaces)
