### ISSUE TITLE
Handle when user overwrites existing cluster registration with different cluster

### ISSUE THREAD

**Issue by EItanya** [solo-io/service-mesh-hub#558]
When the user overwrites an existing cluster registration with `meshctl cluster register --overwrite ...`, if the new cluster is a different cluster, we need to delete the old cluster from our system and perform any relevant cleanup.

[Relevant code here](https://github.com/solo-io/service-mesh-hub/blob/master/services/common/multicluster/watcher/watcher.go#L69)

**Comment by joekelley** [comment]
--overwrite is not implemented in versions >= 0.7
