### ISSUE TITLE
Need to label resources owned by service mesh hub

### ISSUE THREAD

**Issue by christian-posta** [solo-io/service-mesh-hub#583]
```
    labels:
      solo.io/owned-by: service-mesh-hub
```

I do see it on AuthorizationPolicies, but not on Service Entry, Destination Rule, or Virtual Service

**Comment by christian-posta** [comment]
Also... would it make sense at all to always keep service-mesh hub resources in a single namespace to make it easier to tell what's managed and what's not?

**Comment by christian-posta** [comment]
Also, seems Gateway resources are not labeled

**Comment by christian-posta** [comment]
And EnvoyFilter

**Comment by joekelley** [comment]
```yaml
  labels:
    cluster.multicluster.solo.io: smh-remote
    owner.networking.smh.solo.io: service-mesh-hub
