### ISSUE TITLE
Garbage collecting discovered resources

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#584]
Need to implement a garbage collector that runs periodically to ensure that the set of discovered SMH resources matches the real set of resources in each cluster.

This will handle both the case of regular deletes happening while mesh-discovery is online, and missed delete events happening when mesh-discovery is offline to restart.

**Comment by rvennam** [comment]
Hitting this issue - deleted workloads and services from clusters is not reflected `kubectl get meshservices`
