### ISSUE TITLE
Garbage collecting translated resources

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#585]
Periodic garbage collectors (every few seconds) for each of the following:

- [ ] Mesh enforcement disabled (already done)
    - [ ] Delete policy on ingress gateway
    - [ ] Delete global auth enforcement policy
- [ ] TrafficPolicy deletions (essentially garbage collection by ref counting)
    - [ ] Istio
        - [ ] Label VirtualServices with the names of the TrafficPolicies that "own" them (have contributed to their content)
        - [ ] When a traffic policy is deleted, remove its name from all the VirtualService labels that contain it
        - [ ] When a VirtualService has no owners in its ownedBy label delete it
- [ ] AccessControlPolicy deletions
    - [ ] Istio
        - [ ] Label istio AuthorizationPolicies with their owned AccessControlPolicy
        - [ ] Delete istio AuthorizationPolicies for the associated AccessControlPolicy
- [ ] Mesh removed from VirtualMesh 
    - [ ] TBD: de-provision CA so that communication is blocked to the remaining meshes in the VirtualMesh
- [ ] VirtualMesh deleted
    - [ ] the same process for the above point, just for every contained Mesh
    - [ ] Label Gateway and EnvoyFilters with owning VirtualMesh
    - [ ] Label ServiceEntries and DestinationRules with owning VirtualMesh
    - [ ] Delete the above resources with the proper owner label
    - [ ] Be sure to de-allocate IPs from deleted ServiceEntries (TBD: Is this safe to do? If an IP is deallocated from svc A and immediately reallocated to svc B, will that cause problems with any caches anywhere?)

**Comment by harveyxia** [comment]
As this document notes, when translating SMH CRD's to mesh-specific config, some SMH CRD's correspond one-to-one to mesh CRD's while other SMH CRD's correspond many-to-one mesh CRD's. There may be future cases where we change the correspondence from one-to-one/many-to-one.

We can handle any such cases if the garbage collector is agnostic to the numerical relation between SMH/Mesh CRD's, and instead simply garbage collect a mesh CRD if there are no `ownedBy` references.

Furthermore, if the GC is general enough, we can leave all deletions to the garbage collector component, i.e. our translators would never handle any delete events.

**Comment by GrahamGoudeau** [comment]
Re-opening, was mistakenly closed by a missing `resolvesIssue: false` earlier
