### ISSUE TITLE
Restructure docs Getting Started guides

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#595]
User feedback: the docs are a little difficult to navigate.. You have to go to the `Introductory Guides` page first...to install the meshctl cli..and then go back up to `Getting Started` and then jump to `Installing Istio`

![docs-feedback](https://user-images.githubusercontent.com/8539625/79771481-d5e2c700-82fc-11ea-8332-ba84c8e33a7a.png)

**Comment by christian-posta** [comment]
working on this.. should have a PR soon
