### ISSUE TITLE
Access Control Policy example in docs uses wrong context and cluster name

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#605]
https://docs.solo.io/service-mesh-hub/latest/guides/access_control_intro/

The first step port-forwards to bookinfo using:

```
kubectl config use-context remote-cluster-context
```

But then 
1. The kubectl command is invoked with `--context MGMT_PLANE_CTX`
2. The two access control policies at the bottom of the page point to bookinfo in ` cluster: management-plane` as opposed to the remote cluster

**Comment by harveyxia** [comment]
Hey @rvennam:

1. Correct, the AccessControlPolicy should be applied to the management plane context.
2. This is also correct, though the exact cluster name should reference whatever string you supplied to the `--remote-cluster-name` argument for the command `meshctl cluster register`. If you installed using `meshctl demo init`, this should be [`remote-cluster`](https://github.com/solo-io/service-mesh-hub/blob/74d16ec3eeb9a76eed796cd95abcde18cff5b3c8/cli/pkg/tree/demo/init/demo_init_client.go#L80).
