### ISSUE TITLE
Multicluster communication docs should mention kicking istiod

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#609]
https://docs.solo.io/service-mesh-hub/latest/guides/multicluster_communication/

This doesn't mention that, after grouping things in a VirtualMesh, you need to restart istiod to get it to pick up the new root certs.

See:
https://github.com/istio/istio/issues/22993

**Comment by christian-posta** [comment]
So basically we need to completely re-work this guide. Nowhere do we group two different meshes in the guides, which is where this comes into place. We do create a VirtualMesh in the access control guide, but it's for only one mesh. I'm working on a more comprehensive "identity federation" guide...
