### ISSUE TITLE
meshctl demo cleanup deletes ALL kind clusters

### ISSUE THREAD

**Issue by john-a-joyce** [solo-io/service-mesh-hub#641]
I thought I would try service-mesh-hub so I downloaded meshctl launched "mesh demo init" and was pleased at how easy it was to jump in and try things.  I then tried to cleanup using "mesh demo cleanup" and was horrified to see it was cycling through all the kind clusters I had on my machine and deleting them regardless of the origin.  No warning or "do you want to proceed" prompt.

**Comment by christian-posta** [comment]
OUCH! We'll get that cleaned up asap. Sorry about that!

**Comment by christian-posta** [comment]
will be in next release, thx for opening the issue
