### ISSUE TITLE
Appmesh VirtualNode + VirtualRouter listener protocol

### ISSUE THREAD

**Issue by harveyxia** [solo-io/service-mesh-hub#741]
SMH needs a way to know what network protocol (tcp, http, http2, grpc) to use for VirtualNodes and VirtualRouters.

Istio allows users to explicitly configure the protocol through the [Service spec's port name prefix](https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/). We could adopt a similar approach—use k8s Service.spec.ports[n].name prefix for the VirtualRouter listener protocol, and k8s Deployment container port name prefix for the VirtualNode listener protocol.

@yuval-k

**Comment by joekelley** [comment]
I believe this is not an issue when interfacing with the app mesh API via the app mesh controller
