### ISSUE TITLE
Mesh Type: (istio1.6) is not one of the supported Mesh types [istio]

### ISSUE THREAD

**Issue by amartyamandal** [solo-io/service-mesh-hub#810]
Mesh Type: (istio1.6) is not one of the supported Mesh types [istio]
I am running following script in a jenkin job 
https://raw.githubusercontent.com/amartyamandal/k8s_practice/master/Cluster/meshub/add-managment-plane.sh

My cloud provider is DigitalOcean and getting following output 
Switched to context "do-tor1-dgo-management-plane".
Attempting to download meshctl version v0.5.0
Downloading meshctl-linux-amd64...
Download complete!, validating checksum...
Checksum valid.
meshctl was successfully installed 🎉

Add the Service Mesh Hub CLI to your path with:
  export PATH=$HOME/.service-mesh-hub/bin:$PATH

Now run:
  meshctl install     # install Service Mesh Hub management plane
Please see visit the Service Mesh Hub website for more info:  https://www.solo.io/products/service-mesh-hub/
Creating namespace service-mesh-hub... Done.
Starting Service Mesh Hub installation...
Service Mesh Hub successfully installed!
Service Mesh Hub has been installed to namespace service-mesh-hub
Successfully registered cluster management-plane.✅ Kubernetes API
-----------------
✅ Kubernetes API server is reachable
✅ running the minimum supported Kubernetes version (required: >=1.13)

❌ Service Mesh Hub Management Plane
------------------------------------
✅ installation namespace exists
❌ components are running
	Message: Container csr-agent in pod csr-agent-85b4f5b899-hhg7r is waiting: ContainerCreating ()
	Hint: try running either `kubectl -n service-mesh-hub describe pod csr-agent-85b4f5b899-hhg7r` or `kubectl -n service-mesh-hub logs csr-agent-85b4f5b899-hhg7r`

❌ Service Mesh Hub check found errors
Error: check failed
Error: Mesh Type: (istio1.6) is not one of the supported Mesh types [istio]

**To Reproduce**
Please use the same script
https://raw.githubusercontent.com/amartyamandal/k8s_practice/master/Cluster/meshub/add-managment-plane.sh

**Expected behavior**
I should work with istio 1.6

**Comment by amartyamandal** [comment]
I changed the vs to istio1.5 same issue

**Comment by harveyxia** [comment]
Hey @amartyamandal, thanks for filing this issue. Try running `meshctl mesh install istio...`—Service Mesh Hub v0.5.0 doesn't distinguish different Istio versions, meshctl [just uses "istio"](https://github.com/solo-io/service-mesh-hub/blob/753d30081ddc9dd433f769d8f09f6f05ee80209a/cli/pkg/tree/mesh/install/install_command.go#L57) to refer to Istio 1.5. Let me know whether that works for you.

We're currently working towards a release that will have support for installing Istio 1.6
