### ISSUE TITLE
no matches for kind "VirtualMesh" in version "networking.smh.solo.io/v1alpha1"

### ISSUE THREAD

**Issue by amartyamandal** [solo-io/service-mesh-hub#811]
**Describe the bug**
no matches for kind "VirtualMesh" in version "networking.smh.solo.io/v1alpha1"

**To Reproduce**
I am trying to create a virtualmesh as described here 
https://docs.solo.io/service-mesh-hub/latest/guides/federate_identity/#user-provided-certificates

**Expected behavior**
it should recognize the resource

**Comment by harveyxia** [comment]
Hi @amartyamandal, thanks for reporting this issue. Our docs are tracking the master branch (which has renamed `zephyr` to `smh`, not the latest release. https://github.com/solo-io/service-mesh-hub/pull/813, once deployed, should address this
