### ISSUE TITLE
Istio 1.7 support

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/service-mesh-hub#817]
**Is your feature request related to a problem? Please describe.**
Istio 1.7 is scheduled to be released on Aug 11

Timeline from Istio project
- Warn on Slack/Discuss about the imminent branch cut: July 14th, 17th, 20th 2020.
- Branch Cut: July 21, 2020
- 1st Async testing day kick off (1 week): July 29th, 2020
- 2nd Async testing day kick off: August 4th, 2020
- Release Date: August 11th, 2020

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
link to Istio release schedule https://github.com/istio/istio/wiki/Istio-Release-1.7

**Comment by joekelley** [comment]
Istio 1.7 is supported in v0.7.1
