### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by harveyxia** [solo-io/service-mesh-hub#883]
**New Features**
- Istio 1.7 support
- Discovery supports discovery of k8s workloads controlled by DaemonSets and StatefulSet in addition to Deployments
- TrafficPolicy translation, add support for multicluster subset routing

**Stability improvements**
- Overhaul the architecture of discovery and networking
  - Stabilize reconciliation
- Stabilize garbage collection, now scoped to SMH managed objects
- Expose introspection data for debugging
- Reorganize code for clarity and concision

**Breaking Changes**
- CRD renames
  - “MeshService” to “TrafficTarget”
  - “MeshWorkload” to “Workload”
  - “AccessControlPolicy” to “AccessPolicy”
- Dropped support for `meshctl mesh install`
- Temporarily drop support for Appmesh
- Temporarily drop support for EKS cluster discovery

**Comment by joekelley** [comment]
🎉
