### ISSUE TITLE
Update docs to use the convention mgmt-cluster

### ISSUE THREAD

**Issue by ned1313** [solo-io/service-mesh-hub#915]
**Describe the requested changes**
All docs should use `mgmt-cluster` to refer to the management cluster created by the `meshctl demo` command.

This should replace any references to `management-cluster` or `management-plane`.

**Comment by ashleywang1** [comment]
On this page:
https://docs.solo.io/service-mesh-hub/main/guides/multicluster_communication/

new-remote-cluster --> remote-cluster
