### ISSUE TITLE
Usage Patterns doc

### ISSUE THREAD

**Issue by joekelley** [solo-io/service-mesh-hub#929]
**Describe the requested changes**
Let's create a Usage Patterns section in the docs, perhaps under Concepts. A usage pattern can be defined as a convention or best practice of using the Service Mesh Hub API to achieve a particular operational goal.

We can use this issue to define an initial set of usage patterns.

- [x] `Multicluster Service Identity` -- by defining a globally unique "identity" label for like services, users can write TrafficPolicies and AccessPolicies that apply to all instances of a given application throughout your environment.

**Comment by bettyjunod** [comment]
This is a great addition to docs!

Suggestion: create a menu item called Usage Patterns, Examples, Best Practices, or Use Cases..

This can be nested under an existing item like Guides or as a top level menu item.

**Comment by ned1313** [comment]
I'm going to start by adding a subsection call Usage Patterns under Operations.

**Comment by joekelley** [comment]
closing this for now, please suggest new usage patterns in follow-up issues
