### ISSUE TITLE
Meshctl needs --api-server-address argument for Kind

### ISSUE THREAD

**Issue by ned1313** [solo-io/service-mesh-hub#935]
**Describe the requested changes**
The setup guide should make note that the `meshctl cluster register` and `meshctl install` commands need the `--api-server-address` argument when using Kind to host the clusters.

**Link to any relevant existing docs**
1. https://docs.solo.io/service-mesh-hub/latest/setup/

**Comment by jenshu** [comment]
is it possible to change the commands to get the api server address automatically via script, like the demo command does? https://github.com/solo-io/service-mesh-hub/blob/main/pkg/meshctl/commands/demo/common/initialize/common.go#L157
