### ISSUE TITLE
meshctl not respecting KUBECONFIG env var

### ISSUE THREAD

**Issue by ekarlso** [solo-io/service-mesh-hub#945]
**Describe the bug**
For the management plane cluster meshctl is not respecting the KUBECONFIG env var setting

**To Reproduce**

```
meshctl describe traffictarget
```

**Expected behavior**
Not having to --kubeconfig when doing *meshctl* commands.

**Additional context**
Add any other context about the problem here, e.g.
0.7.3
k8s 1.16.13

**Comment by ekarlso** [comment]
This was fixed in 0.7.3 / 0.7.4

**Comment by joekelley** [comment]
Ran into this on 0.7.5.

Steps to reproduce:
- create a kubeconfig and store it somewhere like `/Users/joe/.kube/eksctl/clusters/joe-appmesh-test`
- `export KUBECONFIG=/Users/joe/.kube/eksctl/clusters/joe-appmesh-test`
- `meshctl cluster register --cluster-name foo`
- cluster `foo` will be registered to the cluster in context in the default KUBECONFIG location `/Users/joe/.kube/config`
