### ISSUE TITLE
Bug in README

### ISSUE THREAD

**Issue by Yash5044** [solo-io/service-mesh-hub#984]
**Describe the bug**
The link for code contribution guide of Contribution section in README doesn't work.

**Expected behavior**
The embedded link should redirect to the contribution guide

![Screenshot_20201002_180321](https://user-images.githubusercontent.com/46025582/94923521-9b9b6980-04d9-11eb-98c7-5131e9a94777.png)

**Comment by joekelley** [comment]
Thanks for raising this @Yash5044! I've addressed it in #985.
