### ISSUE TITLE
meshctl debug snapshot

### ISSUE THREAD

**Issue by joekelley** [solo-io/service-mesh-hub#992]
**Is your feature request related to a problem? Please describe.**
We should add a `meshctl debug snapshot` command that exposes the input and output snapshots generated by the Service Mesh Hub controllers at runtime. This will help our users identify discrepancies between the controllers' expected state and the actual state of the resources on their clusters.

**Additional context**
Our controllers already have HTTP endpoints for exposing their recent input and output snapshots: https://github.com/solo-io/service-mesh-hub/blob/v0.8.1/pkg/common/utils/stats/server.go#L17 -- we need to access these endpoints via the CLI and ensure that we can output snapshot data in a user-friendly format.

**Comment by ashleywang1** [comment]
`meshctl debug snapshot` will have flags -f and --zip, and --table.

-f is a toggle to determine which file to output your information to.
--table mode will print out the name, namespace and cluster of specific resources.
--zip is a toggle to zip the output.
