### ISSUE TITLE
Fine-grained control of destinationRules

### ISSUE THREAD

**Issue by antonioberben** [solo-io/service-mesh-hub#996]
**Is your feature request related to a problem? Please describe.**
SMH handles automatically the creation of the destinationRules for the case of Istio. Therefore, in the case a developer wants to have full control of the destinationRules, he can't. The destinationRule is created always with `mTLS: ISTIO_MUTUAL`

**Describe the solution you'd like**
There can be two options to solve this issue:
1. Define an annotation to avoid that SMH auto-generates the destinationRules for an specific service. Similar to: 
```
discovery.smh.solo.io/enabled": "true"
```
2. Define an annotation in service which defines the mTLS value is needed

**Describe alternatives you've considered**
Defined above

**Additional context**
The issue was discussed in slack channel with @harveyxia who found a lead where to find the root cause:
https://github.com/solo-io/service-mesh-hub/blob/4f6ae98e7607da65b7fbb4a7c28909b732863758/pkg/mesh-networking/translation/istio/traffictarget/destinationrule/destination_rule_translator.go#L150

Thank you!

**Comment by joekelley** [comment]
Thanks for filing this @antonioberben! We've discussed a bit internally and on today's [community meeting](https://github.com/solo-io/service-mesh-hub#community-meetings) and are considering a third option as well. We could create a `Settings` CRD where users specify a default mTLS value for all destination rules, and then extend the TrafficPolicy API to allow for overriding the default mTLS value for select services.

**Comment by antonioberben** [comment]
Thank @joekelley for considering this. Can we help in anyway?

**Comment by joekelley** [comment]
@antonioberben we've started work on this task in #1001 and would appreciate any feedback you have on the API

**Comment by antonioberben** [comment]
Hi @joekelley , today I have been thinking in the solution and here my personal opinion.
Creating a new CRD to run a operations like Settings, I think it distorts the idea of operators.
To me, if SMH wants to have settings, like a configuration, it would make more sense to add it as part of other resource which actually runs an action.

**Comment by joekelley** [comment]
Hi @antonioberben, this change was implemented in #1004 and released in Service Mesh Hub 0.9.0. More robust docs will follow soon (#1015), but you'll want to set `settings.mtls.istio.tls_mode=DISABLED` when installing/upgrading via helm if you want to disable mTLS for all DestinationRules. To modify the settings after installation, use `kubectl edit settings -n service-mesh-hub settings`. 

Alternatively or in addition to the global setting, you can also use the TrafficPolicy API to modify the mTLS settings for specific TrafficTargets. API reference here: https://docs.solo.io/service-mesh-hub/latest/reference/api/traffic_policy/#networking.smh.solo.io.TrafficPolicySpec.MTLS

Thank you for your engagement on this issue! We ended up moving forward with the global Settings CRD and TrafficPolicy overrides for mTLS config. The Settings object allows users to modify the global default at runtime; the Settings resource is used by the networking controller to inform translation behavior just like TrafficPolicies, VirtualMeshes, and all our other API objects. By not tying mTLS defaults to the VirtualMesh CRD, users with less-complex use cases are able to forego the VirtualMesh CRD entirely, while still being able to modify mTLS behavior on a per-service level via the new fields on the TrafficPolicy.

I'll close this issue for now, but please try out the new mTLS APIs and let us know if you run into any issues.
